### ISSUE TITLE
有个问题  上传的头像图片不会上传

### ISSUE THREAD

**Issue by zhujitop** [sy-records/wordpress-qcloud-cos#8]
个人资料这里有个头像上传，上传的头像图片并不会被同步到cos里面去。

但是头像链接却显示cos的域名，所以就造成上传的头像显示不出来。

**Comment by sy-records** [comment]
WordPress的头像都是使用的Gravatar头像啊？
后台的个人资料不是有提示吗？
![image](https://user-images.githubusercontent.com/33931153/77821830-2dd84480-7128-11ea-9b44-702d2519fa5c.png)

**Comment by zhujitop** [comment]
可以上传本地头像的，很多主题都有这个功能。

另外禁用插件之后，上传的图片显示不出来了，看了下图片链接还是cos的域名。

**Comment by sy-records** [comment]
主题功能，插件不可能兼容。自行修改主题代码的上传部分。


禁用插件后不会修改旧的链接，只会还原默认链接。禁用前用插件替换数据库链接。

---原始邮件---
发件人: "zhujitop"<notifications@github.com&gt;
发送时间: 2020年3月28日(周六) 晚上9:08
收件人: "sy-records/wordpress-qcloud-cos"<wordpress-qcloud-cos@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Luffy"<52o@qq52o.cn&gt;;
主题: Re: [sy-records/wordpress-qcloud-cos] 有个问题  上传的头像图片不会上传 (#8)




 
可以上传本地头像的，很多主题都有这个功能。
 
另外禁用插件之后，上传的图片显示不出来了，看了下图片链接还是cos的域名。

**Comment by zhujitop** [comment]
> 主题功能，插件无法兼容。自行修改主题代码的上传部分。替换插件后不会修改旧的链接，只能还原替换链接。替换前用插件替换数据库链接。
> […](#)
> ---原始邮件--- 发件人: "zhujitop"<notifications@github.com&gt; 发送时间: 2020年3月28日(周六) 晚上9:08 收件人: "sy-records/wordpress-qcloud-cos"<wordpress-qcloud-cos@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Luffy"<52o@qq52o.cn&gt;; 主题: Re: [sy-records/wordpress-qcloud-cos] 有个问题 上传的头像图片不会上传 (#8) 可以上传本地头像的，很多主题都有这个功能。 另外禁用插件之后，上传的图片显示不出来了，看了下图片链接还是cos的域名。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是把你这个插件都删掉之后，上传的新图片不显示，图片链接还是cos的域名链接，
看了下服务器本地里面是有的，正常来说都删了，那么上传的新图片应该用默认的地址吧，
你这个都删了，新图片还在用cos域名，所以就显示不出来。
我重新安装个别人的插件，都换不回来了，现在只能用你这个插件才能显示正常，又不能卸载又不能换别人的。。。

还有用你插件批量替换域名，显示执行完成，只是把文章里面的链接都替换成功了，
在后台媒体这里还是显示的cos域名。

**Comment by sy-records** [comment]
没遇到过，明天我试下



---原始邮件---
发件人: "zhujitop"<notifications@github.com&gt;
发送时间: 2020年3月28日(周六) 晚上10:10
收件人: "sy-records/wordpress-qcloud-cos"<wordpress-qcloud-cos@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Luffy"<52o@qq52o.cn&gt;;
主题: Re: [sy-records/wordpress-qcloud-cos] 有个问题  上传的头像图片不会上传 (#8)




  
主题功能，插件无法兼容。自行修改主题代码的上传部分。替换插件后不会修改旧的链接，只能还原替换链接。替换前用插件替换数据库链接。
 …
 ---原始邮件--- 发件人: "zhujitop"<notifications@github.com&gt; 发送时间: 2020年3月28日(周六) 晚上9:08 收件人: "sy-records/wordpress-qcloud-cos"<wordpress-qcloud-cos@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Luffy"<52o@qq52o.cn&gt;; 主题: Re: [sy-records/wordpress-qcloud-cos] 有个问题 上传的头像图片不会上传 (#8) 可以上传本地头像的，很多主题都有这个功能。 另外禁用插件之后，上传的图片显示不出来了，看了下图片链接还是cos的域名。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
是把你这个插件都删掉之后，上传的新图片不显示，图片链接还是cos的域名链接，
 看了下服务器本地里面是有的，正常来说都删了，那么上传的新图片应该用默认的地址吧，
 你这个都删了，新图片还在用cos域名，所以就显示不出来。
 我重新安装个别人的插件，都换不回来了，现在只能用你这个插件才能显示正常，又不能卸载又不能换别人的。。。
 
还有用你插件批量替换域名，显示执行完成，只是把文章里面的链接都替换成功了，
 在后台媒体这里还是显示的cos域名。

**Comment by sy-records** [comment]
你是卸载了还是禁用了插件？

**Comment by zhujitop** [comment]
先禁用插件，发现是这样，然后就直接在后台删了，还是没变。

我就去安装另外一个作者的插件，安装他之后，发现上传的新图片还是你这个的，就又停用了。

现在又安装回你的了，只能用你的。

**Comment by sy-records** [comment]
嗯 测试了一下确实有问题 明天看下修复。替换链接就是替换的文章内容，媒体链接是wp拼接的。

你可以把url前缀修改回原来的以后再卸载，就可以了

**Comment by sy-records** [comment]
@zhujitop 用电脑测试了一下，问题出在禁用插件的钩子上，禁用时删除了cos的配置，导致卸载的时候匹配失败。

**解决方法是不勾选`是否删除配置信息`选项，卸载时就会恢复原URL了。**

**Comment by sy-records** [comment]
发个版本，更新下[v1.6.6](https://github.com/sy-records/wordpress-qcloud-cos/releases/tag/v1.6.6)。
